In [8]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
from sklearn import linear_model
from sklearn.utils import shuffle
import pickle
from matplotlib import style

In [9]:
data=pd.read_csv("student-mat.csv", sep=";")
data


school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
390     MS   M   20       U     LE3       A     2     2  services  services   
391     MS   M   17       U     LE3       T     3     1  services  services   
392     MS   M   21       R     GT3       T     1     1     other     other   
393     MS   M   18       R     LE3       T     3     2  services     other   
394     MS   M   19       U     LE3       T     1     1     other   at_home   

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0    ...      4        3      4     1     1      3        6   5   6   6  
1    ...      5        3      3     1     1      3        4   5   5   6  
2    ...      4        3      2     2     3      3       10   7   8  10  
3    ...      3        2      2     1     1      5        2  15  14  15  
4    ...      4        3      2     1     2      5        4   6  10  10  
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..  
390  ...      5        5      4     4     5      4       11   9   9   9  
391  ...      2        4      5     3     4      2        3  14  16  16  
392  ...      5        5      3     3     3      3        3  10   8   7  
393  ...      4        4      1     3     4      5        0  11  12  10  
394  ...      3        2      3     3     3      5        5   8   9   9  

[395 rows x 33 columns]

In [10]:
data=data[["G1","G2","G3","studytime","failures","absences"]]
data

G1  G2  G3  studytime  failures  absences
0     5   6   6          2         0         6
1     5   5   6          2         0         4
2     7   8  10          2         3        10
3    15  14  15          3         0         2
4     6  10  10          2         0         4
..   ..  ..  ..        ...       ...       ...
390   9   9   9          2         2        11
391  14  16  16          1         0         3
392  10   8   7          1         3         3
393  11  12  10          1         0         0
394   8   9   9          1         0         5

[395 rows x 6 columns]

In [11]:
predict="G3"


In [12]:
x=np.array(data.drop(columns=[predict]))
x

array([[ 5,  6,  2,  0,  6],
       [ 5,  5,  2,  0,  4],
       [ 7,  8,  2,  3, 10],
       ...,
       [10,  8,  1,  3,  3],
       [11, 12,  1,  0,  0],
       [ 8,  9,  1,  0,  5]], dtype=int64)

In [13]:
y=np.array(data[predict])
y

array([ 6,  6, 10, 15, 10, 15, 11,  6, 19, 15,  9, 12, 14, 11, 16, 14, 14,
       10,  5, 10, 15, 15, 16, 12,  8,  8, 11, 15, 11, 11, 12, 17, 16, 12,
       15,  6, 18, 15, 11, 13, 11, 12, 18, 11,  9,  6, 11, 20, 14,  7, 13,
       13, 10, 11, 13, 10, 15, 15,  9, 16, 11, 11,  9,  9, 10, 15, 12,  6,
        8, 16, 15, 10,  5, 14, 11, 10, 10, 11, 10,  5, 12, 11,  6, 15, 10,
        8,  6, 14, 10,  7,  8, 18,  6, 10, 14, 10, 15, 10, 14,  8,  5, 17,
       14,  6, 18, 11,  8, 18, 13, 16, 19, 10, 13, 19,  9, 16, 14, 13,  8,
       13, 15, 15, 13, 13,  8, 12, 11,  9,  0, 18,  0,  0, 12, 11,  0,  0,
        0,  0, 12, 15,  0,  9, 11, 13,  0, 11,  0, 11,  0, 10,  0, 14, 10,
        0, 12,  8, 13, 10, 15, 12,  0,  7,  0, 10,  7, 12, 10, 16,  0, 14,
        0, 16, 10,  0,  9,  9, 11,  6,  9, 11,  8, 12, 17,  8, 12, 11, 11,
       15,  9, 10, 13,  9,  8, 10, 14, 15, 16, 10, 18, 10, 16, 10, 10,  6,
       11,  9,  7, 13, 10,  7,  8, 13, 14,  8, 10, 15,  4,  8,  8, 10,  6,
        0, 17, 13, 14,  7

In [14]:
x_train,x_test,y_train,y_test=sklearn.model_selection.train_test_split(x,y,test_size=0.1)

In [15]:
linear=linear_model.LinearRegression()
linear

LinearRegression()

In [17]:
linear_model.LinearRegression().fit(x_train, y_train)

LinearRegression()

In [198]:
acc=linear.score(x_train,y_train)
acc

0.8178980313843227

In [189]:
predictions=linear.predict(x_test)
predictions

array([ 8.70599362, 14.49270534, 10.71127422,  5.3014584 ,  4.98393905,
        8.95252538, 15.04064711,  8.17882976,  9.44505199,  2.86291163,
        8.76275114, 12.98307255, 10.82478927, 12.54507169,  8.51267957,
       12.12472754, 15.57538004, 12.67847523, 11.97749645,  9.54658443,
        6.22584314, 14.80832974, 19.80986582,  5.08859268, -1.58309751,
        4.16380501, 10.76803174,  5.47557624, -0.32118918,  8.65146787,
        9.37854363, 17.21620028, 11.83342087, 10.50069029,  7.88713625,
        8.27691987,  8.71574445, 11.05181936,  7.93191117,  7.26949882])

In [190]:
for i in range(len(predictions)):
    print(predictions[i],x_train[i],y_test[i])

8.705993620907643 [15 15  2  0  0] 10
14.492705341499706 [ 7 10  4  1  2] 13
10.7112742179079 [14 15  1  0  3] 10
5.301458401086433 [6 5 3 1 0] 8
4.983939047905305 [14 16  1  0  3] 5
8.952525380598065 [13 13  4  0  4] 10
15.040647114905525 [11 11  3  0  3] 15
8.178829762416132 [12 12  2  0 14] 0
9.445051990162016 [12 13  2  0  0] 0
2.8629116258006295 [16 18  2  0  0] 0
8.762751144890306 [18 16  3  0  0] 10
12.98307254820079 [10  8  2  0 14] 12
10.824789265873225 [11  9  2  0 14] 11
12.54507168548041 [15 15  2  0  2] 12
8.512679574894833 [8 9 1 0 0] 0
12.12472754353695 [12 10  2  0  8] 13
15.575380038462637 [10  9  2  0  0] 15
12.678475231361746 [16 15  2  0 10] 13
11.977496445653783 [8 7 2 0 0] 12
9.546584429108362 [7 8 2 3 2] 10
6.225843135120354 [8 7 1 1 7] 8
14.808329741373171 [15 14  3  0  2] 15
19.809865817606383 [12 12  1  0  8] 19
5.088592680989043 [17 18  1  0  0] 0
-1.5830975132997127 [6 0 1 0 0] 0
4.163805014137434 [8 9 2 0 4] 6
10.768031741890562 [15 15  2  0  4] 11
5.475576